module.exports = {
    GROUP_CREATED: "GROUP_CREATED",
    GROUP_DELETED: "GROUP_DELETED",

    MEMBER_ADDED: "MEMBER_ADDED",
    MEMBER_REMOVED: "MEMBER_REMOVED",

    EXPENSE_CREATED: "EXPENSE_CREATED",
    EXPENSE_UPDATED: "EXPENSE_UPDATED",
    EXPENSE_DELETED: "EXPENSE_DELETED",

    SETTLEMENT_CREATED: "SETTLEMENT_CREATED",
};